controllers and views
paulshaun-kdtk/blog-posts pull request #5
Opened 2023-11-20 10:50 UTC by paulshaun-kdtk

# Changes

- configured controllers for all models
- Configured routes
- added basic html in view

2023-11-20 11:04 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @paulshaun-kdtk,

Good job so far!
✔️ Implementation of nested routes
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-20 11:04 UTC, TedLivist commented on config/routes.rb
> +  end
- [ ] Kindly avoid creating and exposing unnecessary routes. We only need the posts' and users' `index` and `show` routes, kindly remove the rest.

  ```
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end
  ```

2023-11-20 11:04 UTC, TedLivist commented on app/controllers/comments_controller.rb
> +# app/controllers/comments_controller.rb
- [ ] Kindly remove this controller as it would have no matching routes after fixing the routes above.

2023-11-20 11:04 UTC, TedLivist commented on app/controllers/likes_controller.rb
> +# app/controllers/likes_controller.rb
- [ ] Kindly remove this controller as it would have no matching routes after fixing the routes above.

2023-11-20 11:04 UTC, TedLivist commented on app/controllers/post_controller.rb
> +
- [ ] Kindly remove these controller actions. We only need the index and show actions.

2023-11-20 11:04 UTC, TedLivist commented on app/controllers/post_controller.rb
> +class PostsController < ApplicationController
- [ ] The file name should be `posts_controller.rb`, not `post_controller.rb`.

2023-11-20 11:04 UTC, TedLivist commented on app/controllers/users_controller.rb
> +
- [ ] Kindly remove these controller actions. We only need the index and show actions.

2023-11-20 11:04 UTC, TedLivist commented on app/views/users/edit.html.erb
> +
- [ ] Kindly remove this view file.

2023-11-20 11:04 UTC, TedLivist commented on app/views/users/new.html.erb
> +
- [ ] Kindly remove this view file.

2023-11-20 11:04 UTC, TedLivist commented on app/views/posts/index.html.erb
> +
- [ ] In addition to this post index view page, you need to create the `app/views/posts/show.html.erb` also to connect with the show action in the posts controller.

2023-11-21 06:56 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @paulshaun-kdtk, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Descriptive Pull Request title & summary. ✔️
- Linters properly setup ✔️
- Users_controller setup for `index` and `show` action ✔️ 
- Posts_controller setup for `index` and `show` action ✔️ 
- Good use of Git flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-23 19:30 UTC, merged